// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0bo_trPRqy0EAOjgU1acR01IrR63pTg',
    appId: '1:529404454167:web:82487c0fb07ec80fe38352',
    messagingSenderId: '529404454167',
    projectId: 'socialapp-9c936',
    authDomain: 'socialapp-9c936.firebaseapp.com',
    storageBucket: 'socialapp-9c936.appspot.com',
    measurementId: 'G-1RJL12R2LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd_HbypzmdkFAgu3rO95wCb6ICiAt0oFY',
    appId: '1:529404454167:android:ff1db6c4724a14e2e38352',
    messagingSenderId: '529404454167',
    projectId: 'socialapp-9c936',
    storageBucket: 'socialapp-9c936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ASKjYbaqfwb9KHgUyxbupzjP_8rRwJQ',
    appId: '1:529404454167:ios:3d95b4ec7c70412ee38352',
    messagingSenderId: '529404454167',
    projectId: 'socialapp-9c936',
    storageBucket: 'socialapp-9c936.appspot.com',
    iosClientId: '529404454167-lbeasi1bgcmtgsevie5egpt273b0ckcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myUdemyApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ASKjYbaqfwb9KHgUyxbupzjP_8rRwJQ',
    appId: '1:529404454167:ios:3d95b4ec7c70412ee38352',
    messagingSenderId: '529404454167',
    projectId: 'socialapp-9c936',
    storageBucket: 'socialapp-9c936.appspot.com',
    iosClientId: '529404454167-lbeasi1bgcmtgsevie5egpt273b0ckcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myUdemyApps',
  );
}
